**Input Matrix**

   [1 0 0]
   [0 1 0]
   [0 1 0]

we need to calculate the determinant of a given 3×3 matrix using Python.
The determinant helps in identifying whether the matrix is singular or non-singular.

**Algorithm**

1. Input the 3×3 matrix.
2. Compute the determinant using a built-in function.
3. Display the determinant value.
4. Check if the matrix is singular or non-singular.

In [1]:
import numpy as np

# Sample input matrix
A = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 1, 0]])

# Calculate determinant
det_A = np.linalg.det(A)

print("Determinant of the matrix:", det_A)

# Check singularity
if np.isclose(det_A, 0):
    print("Matrix is Singular (Determinant = 0)")
else:
    print("Matrix is Non-Singular (Determinant ≠ 0)")


Determinant of the matrix: 0.0
Matrix is Singular (Determinant = 0)


**Time Complexity**

Determinant calculation for an

n×n matrix: O(n³)

Time Complexity: O(n³)

**Space Complexity**

Only constant extra variables are used

Space Complexity: O(1)